// Code generated by "stringer -type=Event"; DO NOT EDIT.

package kratos

import "strconv"

const _Event_name = "ErrorOpenPingPongCloseMessageDone"

var _Event_index = [...]uint8{0, 5, 9, 13, 17, 22, 29, 33}

func (i Event) String() string {
	i -= 1
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
